# Generated by Django 5.0.1 on 2024-02-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[(0, 'Daily'), (1, 'Every Monday'), (2, 'Every Tuesday'), (3, 'Every Wednesday'), (4, 'Every Thursday'), (5, 'Every Friday'), (6, 'Every Saturday'), (7, 'Every Sunday')], default='0', max_length=1, verbose_name='Periodicity of action'),
        ),
    ]
